/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#1D4ED8",
          50: "#F0F5FF",
          100: "#DFE8FF",
          200: "#BDD3FF",
          300: "#9BBEFF",
          400: "#7FA8FF",
          500: "#1D4ED8",
          600: "#1D4ED8",
          700: "#1937B8",
          800: "#142A8F",
          900: "#0F1D66",
          950: "#0D1B70",
        },
      },
    },
  },
  safelist: [
    // Primary colors
    "bg-primary",
    "text-primary",
    "border-primary",
    "hover:bg-primary",
    "hover:text-primary",
    "hover:border-primary",
    "focus:border-primary",
    "focus:ring-primary",
    "from-primary",
    "to-primary",
    "via-primary",
    "bg-primary/10",
    "bg-primary-50",
    "bg-primary-100",
    "bg-primary-200",
    "bg-primary-300",
    "bg-primary-400",
    "bg-primary-500",
    "bg-primary-600",
    "bg-primary-700",
    "bg-primary-800",
    "bg-primary-900",
    "text-primary-50",
    "text-primary-100",
    "text-primary-200",
    "text-primary-300",
    "text-primary-400",
    "text-primary-500",
    "text-primary-600",
    "text-primary-700",
    "text-primary-800",
    "text-primary-900",
  ],
  plugins: [],
};
